server.port: @server-port@

management.security.enabled: false
logging:
  level.ru.natalietours: DEBUG
  file: logs/app.log

unisender:
  url:
    send: https://one.unisender.com/ru/transactional/api/v1/email/send.json
    unsubscribeUrl: unsubscribeUrl
  apiKey: 6id8b498n519kqeqkfn7iir7osuwau9xmc9kff5e
  username: tebuchet@gmail.com

app:
  timezone: "Europe/Moscow"
  heartbeat: 60